name: obra_limpa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  get: ^4.1.4
  intl:
  fancy_bottom_navigation: ^0.3.3
  ionicons: ^0.1.2
  getwidget: ^2.0.3
  lottie: ^1.0.1
  rounded_loading_button: ^2.0.5
  motion_toast: ^1.0.0
  oktoast: ^3.0.0
  fluttertoast: ^8.0.7
  
dev_dependencies:
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter  

flutter_native_splash:
  background_image: assets/imagens/splashNative.png 

flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: assets/imagens/icon.png


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/imagens/

  fonts:
    - family: TwentiethCenturyMT
      fonts:
      - asset: assets/fonts/TwentiethCenturyMTLight.ttf
        weight: 100
      - asset: assets/fonts/TwentiethCenturyMTSemiMedium.ttf
        weight: 200
      - asset: assets/fonts/TwentiethCenturyMTMedium.ttf
        weight: 300
      - asset: assets/fonts/TwentiethCenturyMTMediumCondensed.ttf
        weight: 400
      - asset: assets/fonts/TwentiethCenturyMTSemiBold.ttf
        weight: 500
      - asset: assets/fonts/TwentiethCenturyMTBold.ttf
        weight: 600
      - asset: assets/fonts/TwentiethCenturyMTBoldCondensed.ttf
        weight: 700
      - asset: assets/fonts/TwentiethCenturyMTExtraBoldCondensed.ttf
        weight: 800
      - asset: assets/fonts/TwentiethCenturyMTExtraBold.ttf
        weight: 900
         
      #Itálico
      - asset: assets/fonts/TwentiethCenturyMTLightItalic.ttf
        style: italic
        weight: 100
      - asset: assets/fonts/TwentiethCenturyMTMediumItalic.ttf
        style: italic
        weight: 200
      - asset: assets/fonts/TwentiethCenturyMTBoldItalic.ttf
        style: italic
        weight: 300
      - asset: assets/fonts/TwentiethCenturyMTExtraBoldItalic.ttf
        style: italic
        weight: 400
      - asset: assets/fonts/TwentiethCenturyMTUltraBoldItalic.ttf
        style: italic
        weight: 500
      